export type RootStackParamList = {
  Splash: undefined;
  Home: undefined;
  Login: undefined;
  EmailLogin: undefined;
  EmailSignUp: undefined;
  PrivacyUsePolicy: undefined;
  PrivacySharePolicy: undefined;
  EmailSignUpComplete: undefined;
  LifestyleStart: undefined;
  LifestyleQuestion: undefined;
  LifestyleComplete: undefined;
  BiometricStart: undefined;
  BiometricOverview: undefined;
  BiometricComplete: undefined;
  ReportStart: undefined;
  ReportResult: undefined;
  Mypage: undefined;
  DementiaInfoList: undefined;
  DementiaInfoDetail: undefined;
};